# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34e22a117124364f66cc014c05bb868b908781aa6ad28cc8757632bc660e14ac4f0e9ee6bb77e8bb08b36622b51407f2df027d7bbf693cd062791bc55d628395

test:
  secret_key_base: 6ce8262afb3b00afcb90c277b3a77ad30c10aad7295c70bc7d2d260e406566a7e49294ba827cf2ad546246eea74e71f774c3c49ae7b592ae18574463b72619f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
